version: '3'
services:
  db:
    image: postgres:9.5
  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/devise_with_vue
    ports:
      - "8080:8080"
      - "3035:3035"
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/devise_with_vue
    depends_on:
      - db
      - webpacker
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    stdin_open: true
    tty: true
